// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StatsClient is the client API for Stats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsClient interface {
	GetAllCovidCasesStream(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Stats_GetAllCovidCasesStreamClient, error)
	GetAllCovidCases(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CovidCaseStatEntryList, error)
	GetAllStocksStream(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Stats_GetAllStocksStreamClient, error)
	GetAllStocks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StockList, error)
	GetAllVaccineEntries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VaccineEntryList, error)
}

type statsClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsClient(cc grpc.ClientConnInterface) StatsClient {
	return &statsClient{cc}
}

func (c *statsClient) GetAllCovidCasesStream(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Stats_GetAllCovidCasesStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Stats_ServiceDesc.Streams[0], "/covid_stats.Stats/GetAllCovidCasesStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &statsGetAllCovidCasesStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Stats_GetAllCovidCasesStreamClient interface {
	Recv() (*CovidCaseStatEntry, error)
	grpc.ClientStream
}

type statsGetAllCovidCasesStreamClient struct {
	grpc.ClientStream
}

func (x *statsGetAllCovidCasesStreamClient) Recv() (*CovidCaseStatEntry, error) {
	m := new(CovidCaseStatEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *statsClient) GetAllCovidCases(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CovidCaseStatEntryList, error) {
	out := new(CovidCaseStatEntryList)
	err := c.cc.Invoke(ctx, "/covid_stats.Stats/GetAllCovidCases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetAllStocksStream(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Stats_GetAllStocksStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Stats_ServiceDesc.Streams[1], "/covid_stats.Stats/GetAllStocksStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &statsGetAllStocksStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Stats_GetAllStocksStreamClient interface {
	Recv() (*Stock, error)
	grpc.ClientStream
}

type statsGetAllStocksStreamClient struct {
	grpc.ClientStream
}

func (x *statsGetAllStocksStreamClient) Recv() (*Stock, error) {
	m := new(Stock)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *statsClient) GetAllStocks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StockList, error) {
	out := new(StockList)
	err := c.cc.Invoke(ctx, "/covid_stats.Stats/GetAllStocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetAllVaccineEntries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VaccineEntryList, error) {
	out := new(VaccineEntryList)
	err := c.cc.Invoke(ctx, "/covid_stats.Stats/GetAllVaccineEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServer is the server API for Stats service.
// All implementations must embed UnimplementedStatsServer
// for forward compatibility
type StatsServer interface {
	GetAllCovidCasesStream(*Empty, Stats_GetAllCovidCasesStreamServer) error
	GetAllCovidCases(context.Context, *Empty) (*CovidCaseStatEntryList, error)
	GetAllStocksStream(*Empty, Stats_GetAllStocksStreamServer) error
	GetAllStocks(context.Context, *Empty) (*StockList, error)
	GetAllVaccineEntries(context.Context, *Empty) (*VaccineEntryList, error)
	mustEmbedUnimplementedStatsServer()
}

// UnimplementedStatsServer must be embedded to have forward compatible implementations.
type UnimplementedStatsServer struct {
}

func (UnimplementedStatsServer) GetAllCovidCasesStream(*Empty, Stats_GetAllCovidCasesStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllCovidCasesStream not implemented")
}
func (UnimplementedStatsServer) GetAllCovidCases(context.Context, *Empty) (*CovidCaseStatEntryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCovidCases not implemented")
}
func (UnimplementedStatsServer) GetAllStocksStream(*Empty, Stats_GetAllStocksStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllStocksStream not implemented")
}
func (UnimplementedStatsServer) GetAllStocks(context.Context, *Empty) (*StockList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllStocks not implemented")
}
func (UnimplementedStatsServer) GetAllVaccineEntries(context.Context, *Empty) (*VaccineEntryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllVaccineEntries not implemented")
}
func (UnimplementedStatsServer) mustEmbedUnimplementedStatsServer() {}

// UnsafeStatsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServer will
// result in compilation errors.
type UnsafeStatsServer interface {
	mustEmbedUnimplementedStatsServer()
}

func RegisterStatsServer(s grpc.ServiceRegistrar, srv StatsServer) {
	s.RegisterService(&Stats_ServiceDesc, srv)
}

func _Stats_GetAllCovidCasesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StatsServer).GetAllCovidCasesStream(m, &statsGetAllCovidCasesStreamServer{stream})
}

type Stats_GetAllCovidCasesStreamServer interface {
	Send(*CovidCaseStatEntry) error
	grpc.ServerStream
}

type statsGetAllCovidCasesStreamServer struct {
	grpc.ServerStream
}

func (x *statsGetAllCovidCasesStreamServer) Send(m *CovidCaseStatEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _Stats_GetAllCovidCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetAllCovidCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/covid_stats.Stats/GetAllCovidCases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetAllCovidCases(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetAllStocksStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StatsServer).GetAllStocksStream(m, &statsGetAllStocksStreamServer{stream})
}

type Stats_GetAllStocksStreamServer interface {
	Send(*Stock) error
	grpc.ServerStream
}

type statsGetAllStocksStreamServer struct {
	grpc.ServerStream
}

func (x *statsGetAllStocksStreamServer) Send(m *Stock) error {
	return x.ServerStream.SendMsg(m)
}

func _Stats_GetAllStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetAllStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/covid_stats.Stats/GetAllStocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetAllStocks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetAllVaccineEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetAllVaccineEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/covid_stats.Stats/GetAllVaccineEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetAllVaccineEntries(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Stats_ServiceDesc is the grpc.ServiceDesc for Stats service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stats_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "covid_stats.Stats",
	HandlerType: (*StatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllCovidCases",
			Handler:    _Stats_GetAllCovidCases_Handler,
		},
		{
			MethodName: "GetAllStocks",
			Handler:    _Stats_GetAllStocks_Handler,
		},
		{
			MethodName: "GetAllVaccineEntries",
			Handler:    _Stats_GetAllVaccineEntries_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllCovidCasesStream",
			Handler:       _Stats_GetAllCovidCasesStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllStocksStream",
			Handler:       _Stats_GetAllStocksStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stats.proto",
}
